### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by Lorenz-127** [Lorenz-127/2048_Game#1]
### Acceptance Criteria
- Godot 4.3 project is initialized with correct settings
- Git repository is set up with .gitignore file
- README.md file is created with basic project information
- All team members have access to the repository

### Tasks
- [ ] Install Godot 4.3
- [ ] Create new Godot project
- [ ] Initialize Git repository
- [ ] Create and configure .gitignore file
- [ ] Write initial README.md
- [ ] Invite team members to repository
